### ISSUE TITLE
Appium Error - An unknown server-side error occurred while processing the command. Original error: Callback must be a function

### ISSUE THREAD

**Issue by testmonk** [appium/appium-desktop#1173]
## The problem
Receiving the below error while launching the iOS app.
An unknown server-side error occurred while processing the command. Original error: Callback must be a function

##Environment
Mac

- I am running Appium Desktop version _<1.15.1 (1.15.1.20191013.2)>_.

@KazuCocoa Please advice.

**Comment by KazuCocoa** [comment]
Could you share the appium log?

**Comment by testmonk** [comment]
@KazuCocoa Check this out.

[info] [35m[Appium][39m Welcome to Appium v1.15.1
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/sessions[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[GENERIC][39m Calling AppiumDriver.getSessions() with args: []
[debug] [35m[GENERIC][39m Responding to client with driver.getSessions() result: []
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/sessions [39m[32m200[39m [90m6 ms - 40[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"agentPath":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj","app":"/Users/admin/Downloads/mho.ipa","automationName":"XCUITest","bootstrapPath":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent","bundleId":"com.******.devteam","deviceName":"YIP-51","platformName":"iOS","platformVersion":"12.3.1","udid":"00008020-001A65D02188002E","useNewWDA":true,"xcodeOrgId":"849UP4BSN8","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"agentPath":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj","app":"/Users/admin/Downloads/mho.ipa","automationName":"XCUITest","bootstrapPath":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent","bundleId":"com.*****.devteam","deviceName":"YIP-51","platformName":"iOS","platformVersion":"12.3.1","udid":"00008020-001A65D02188002E","useNewWDA":true,"xcodeOrgId":"849UP4BSN8","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1573459507064 (13:35:07 GMT+0530 (IST))
[info] [Appium] Appium v1.15.1 creating new XCUITestDriver (v2.133.1) session
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "agentPath": "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj",
[debug] [BaseDriver]   "app": "/Users/admin/Downloads/mho.ipa",
[debug] [BaseDriver]   "automationName": "XCUITest",
[debug] [BaseDriver]   "bootstrapPath": "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent",
[debug] [BaseDriver]   "bundleId": "com.*****.devteam",
[debug] [BaseDriver]   "deviceName": "YIP-51",
[debug] [BaseDriver]   "platformName": "iOS",
[debug] [BaseDriver]   "platformVersion": "12.3.1",
[debug] [BaseDriver]   "udid": "00008020-001A65D02188002E",
[debug] [BaseDriver]   "useNewWDA": true,
[debug] [BaseDriver]   "xcodeOrgId": "849UP4BSN8",
[debug] [BaseDriver]   "xcodeSigningId": "iPhone Developer",
[debug] [BaseDriver]   "newCommandTimeout": 0,
[debug] [BaseDriver]   "connectHardwareKeyboard": true
[debug] [BaseDriver] }
[info] [BaseDriver] Session created with session id: 9abe478a-8dd3-497a-a526-b880abd95b10[debug] [XCUITest] Available devices: 01b8fb8239c2573d11f928c9e2427a7b73a54518, 74c2448d14432239c7a4d85e62ceb5e669b04726, 00008020-001A65D02188002E
[debug] [XCUITest] Creating iDevice object with udid '00008020-001A65D02188002E'
[info] [XCUITest] Determining device to run tests on: udid: '00008020-001A65D02188002E', real device: true
[info] [XCUITest] Normalized platformVersion capability value '12.3.1' to '12.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1573459517278 (13:35:17 GMT+0530 (IST))[debug] [BaseDriver] Unzipping '/Users/admin/Downloads/mho.ipa'[debug] [BaseDriver] Extracted 139 item(s) from '/Users/admin/Downloads/mho.ipa'
[debug] [BaseDriver] Matched 136 item(s) in the extracted archive. Assuming 'Payload/MHOM.app' is the correct bundle
[info] [BaseDriver] Unzipped local app to '/var/folders/4h/_5y16nvj7n7g1sk8f8smk7lw0000gn/T/20191011-7407-1ogv8lx.uqqo/Payload/MHOM.app'
[error] [XCUITest] TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
[error] [XCUITest]     at makeStatsCallback (fs.js:178:11)
[error] [XCUITest]     at fs.stat (fs.js:914:14)
[error] [XCUITest]     at Object.fs.stat (ELECTRON_ASAR.js:306:16)
[error] [XCUITest]     at Object.tryCatcher (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
[error] [XCUITest]     at Object.ret [as stat] (eval at makeNodePromisifiedEval (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:15:23)
[error] [XCUITest]     at stat (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/appium-support/lib/util.js:226:72)
[error] [XCUITest]     at tryCatcher (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
[error] [XCUITest]     at MappingPromiseArray._promiseFulfilled (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/map.js:61:38)
[error] [XCUITest]     at MappingPromiseArray.PromiseArray._iterate (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promise_array.js:114:31)
[error] [XCUITest]     at MappingPromiseArray.init (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promise_array.js:78:10)
[error] [XCUITest]     at MappingPromiseArray._asyncInit (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/map.js:30:10)
[error] [XCUITest]     at _drainQueueStep (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:142:12)
[error] [XCUITest]     at _drainQueue (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:131:9)
[error] [XCUITest]     at Async._drainQueues (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:147:5)
[error] [XCUITest]     at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
[error] [XCUITest]     at runCallback (timers.js:696:18)
[error] [XCUITest]     at tryOnImmediate (timers.js:667:5)
[error] [XCUITest]     at processImmediate (timers.js:649:5)
[info] [DevCon Factory] Releasing connections for 00008020-001A65D02188002E device on any port number
[info] [DevCon Factory] No cached connections have been found
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1573459524258 (13:35:24 GMT+0530 (IST))
[debug] [MJSONWP] Encountered internal error running command: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
[debug] [MJSONWP]     at makeStatsCallback (fs.js:178:11)
[debug] [MJSONWP]     at fs.stat (fs.js:914:14)
[debug] [MJSONWP]     at Object.fs.stat (ELECTRON_ASAR.js:306:16)
[debug] [MJSONWP]     at Object.tryCatcher (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
[debug] [MJSONWP]     at Object.ret [as stat] (eval at makeNodePromisifiedEval (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:15:23)
[debug] [MJSONWP]     at stat (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/appium-support/lib/util.js:226:72)
[debug] [MJSONWP]     at tryCatcher (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
[debug] [MJSONWP]     at MappingPromiseArray._promiseFulfilled (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/map.js:61:38)
[debug] [MJSONWP]     at MappingPromiseArray.PromiseArray._iterate (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promise_array.js:114:31)
[debug] [MJSONWP]     at MappingPromiseArray.init (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promise_array.js:78:10)
[debug] [MJSONWP]     at MappingPromiseArray._asyncInit (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/map.js:30:10)
[debug] [MJSONWP]     at _drainQueueStep (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:142:12)
[debug] [MJSONWP]     at _drainQueue (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:131:9)
[debug] [MJSONWP]     at Async._drainQueues (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:147:5)
[debug] [MJSONWP]     at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
[debug] [MJSONWP]     at runCallback (timers.js:696:18)
[debug] [MJSONWP]     at tryOnImmediate (timers.js:667:5)
[debug] [MJSONWP]     at processImmediate (timers.js:649:5)
[info] [HTTP] <-- POST /wd/hub/session 500 17199 ms - 164
[info] [HTTP] 
[info] [HTTP] [37m-->[39m [37mDELETE[39m [37m/wd/hub/session[39m
[info] [HTTP] {}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[info] [HTTP] <-- DELETE /wd/hub/session 404 3 ms - 57
[info] [HTTP]

**Comment by KazuCocoa** [comment]
Thanks.

Could you try current `appium@beta` with nodejs 10+? https://github.com/appium/appium-desktop#connect-to-local-appium-server

**Comment by mounikaakuthota12** [comment]
Hey did issue got resolved? @KazuCocoa

**Comment by mounikaakuthota12** [comment]
I see the same error below is my appium log
[BaseDriver] Session created with session id: c91915a9-3d48-426c-a660-a35abdf43b66
[XCUITest] Current user: 'makut0812'
[XCUITest] Available devices: 00008020-00110C543698002E
[XCUITest] Creating iDevice object with udid '00008020-00110C543698002E'
[XCUITest] Determining device to run tests on: udid: '00008020-00110C543698002E', real device: true
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1573785186788 (18:33:06 GMT-0800 (PST))
[BaseDriver] Using local app '/Users/makut0812/Downloads/CBS_v7.2.50_b2520_AdHoc.ipa'
[BaseDriver] Will reuse previously cached application at '/var/folders/rg/fyxglx096jl_8mrt2lly40k00000gq/T/20191014-1791-1c0e8z6.4jii/Payload/CBS.app'
[XCUITest] TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
[XCUITest]     at makeStatsCallback (fs.js:178:11)
[XCUITest]     at fs.stat (fs.js:914:14)
[XCUITest]     at Object.fs.stat (ELECTRON_ASAR.js:306:16)
[XCUITest]     at Object.tryCatcher (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
[XCUITest]     at Object.ret [as stat] (eval at makeNodePromisifiedEval (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promisify.js:184:12), :15:23)
[XCUITest]     at stat (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/appium-support/lib/util.js:260:72)
[XCUITest]     at tryCatcher (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
[XCUITest]     at MappingPromiseArray._promiseFulfilled (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/map.js:61:38)
[XCUITest]     at MappingPromiseArray.PromiseArray._iterate (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promise_array.js:114:31)
[XCUITest]     at MappingPromiseArray.init (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promise_array.js:78:10)
[XCUITest]     at MappingPromiseArray._asyncInit (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/map.js:30:10)
[XCUITest]     at _drainQueueStep (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:142:12)
[XCUITest]     at _drainQueue (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:131:9)
[XCUITest]     at Async._drainQueues (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:147:5)
[XCUITest]     at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
[XCUITest]     at runCallback (timers.js:696:18)
[XCUITest]     at tryOnImmediate (timers.js:667:5)
[XCUITest]     at processImmediate (timers.js:649:5)
[DevCon Factory] Releasing connections for 00008020-00110C543698002E device on any port number
[DevCon Factory] No cached connections have been found
[BaseDriver] Event 'newSessionStarted' logged at 1573785186892 (18:33:06 GMT-0800 (PST))
[MJSONWP] Encountered internal error running command: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
[MJSONWP]     at makeStatsCallback (fs.js:178:11)
[MJSONWP]     at fs.stat (fs.js:914:14)
[MJSONWP]     at Object.fs.stat (ELECTRON_ASAR.js:306:16)
[MJSONWP]     at Object.tryCatcher (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
[MJSONWP]     at Object.ret [as stat] (eval at makeNodePromisifiedEval (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promisify.js:184:12), :15:23)
[MJSONWP]     at stat (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/appium-support/lib/util.js:260:72)
[MJSONWP]     at tryCatcher (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
[MJSONWP]     at MappingPromiseArray._promiseFulfilled (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/map.js:61:38)
[MJSONWP]     at MappingPromiseArray.PromiseArray._iterate (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promise_array.js:114:31)
[MJSONWP]     at MappingPromiseArray.init (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promise_array.js:78:10)
[MJSONWP]     at MappingPromiseArray._asyncInit (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/map.js:30:10)
[MJSONWP]     at _drainQueueStep (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:142:12)
[MJSONWP]     at _drainQueue (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:131:9)
[MJSONWP]     at Async._drainQueues (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:147:5)
[MJSONWP]     at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
[MJSONWP]     at runCallback (timers.js:696:18)
[MJSONWP]     at tryOnImmediate (timers.js:667:5)
[MJSONWP]     at processImmediate (timers.js:649:5)
[HTTP] <-- POST /wd/hub/session 500 124 ms - 164
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 1 ms - 57
[HTTP]

**Comment by KazuCocoa** [comment]
It reproduced when I built the appium server with NodeJS v8.16.2, but it was resolved in v10.16.0 and v12.12.0. (Appium server) I also tried with Appium Desktop 1.15.1 on my env.

```
[XCUITest] TypeError: "callback" argument must be a function
[XCUITest]     at makeStatsCallback (fs.js:148:11)
[XCUITest]     at Object.fs.stat (fs.js:924:14)
[XCUITest]     at Object.stat (/Users/kazu/GitHub/appium-xcuitest-driver/node_modules/bluebird/js/release/util.js:16:23)
[XCUITest]     at Object.ret [as stat] (eval at makeNodePromisifiedEval (/Users/kazu/GitHub/appium/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:15:23)
[XCUITest]     at _bluebird.default.map (/Users/kazu/GitHub/appium-xcuitest-driver/node_modules/appium-support/lib/util.js:260:72)
[XCUITest]     at tryCatcher (/Users/kazu/GitHub/appium-xcuitest-driver/node_modules/bluebird/js/release/util.js:16:23)
[XCUITest]     at MappingPromiseArray._promiseFulfilled (/Users/kazu/GitHub/appium-xcuitest-driver/node_modules/bluebird/js/release/map.js:68:38)
```

So, I assumed older node version affected your runtime.
(We support NodeJS 10+ env since Appium 1.14)

Could you remove older node versions from your machine?
built-in node version on AD is 10+, but potentially other global environment affects he AD.

**Comment by mounikaakuthota12** [comment]
Yes, as I mentioned above I have node version V12.12.0 & Apium v1.15.1..You would recommend to delete Appium Desktop and download new one?

**Comment by pramod200887** [comment]
Hi All, 

I am pretty new here in Appium and world of Automation here. I am getting above error since last week , I tried multiple solution, such as updating node version to latest one , updating Appium desktop version to 1.15.1 , clean build and update but still above error. Please let me know if any breakthrough achieved.
<img width="1126" alt="Screen Shot 2019-11-19 at 12 01 33 PM" src="https://user-images.githubusercontent.com/41515596/69181680-63a75580-0ac4-11ea-8c5f-cb0984cde9d4.png">

**Comment by KazuCocoa** [comment]
I've added information about NodeJS version in about window. I hope it will help to figure out the cause... (What node version has this issue)

As a workaround, you  also can connect to local Appium server
https://github.com/appium/appium-desktop#connect-to-local-appium-server

If the error is node version specific issue, the local appium server with another nodejs version will fix it, I predict...
https://github.com/appium/appium-desktop/issues/1173#issuecomment-554448586

**Comment by KseniaBudlianska** [comment]
I have `An unknown server-side error occurred while processing the command. Original error: Callback must be a function` issue with the below versions. @KazuCocoa Can you please help me to figure out what can be the problem? As I can see by your #1173 comment I have all correct versions, but it doesn't resolve the problem.

` $ appium -v`
1.16.0
` $ node -v`
v13.6.0
` $ npm -v`
6.13.4

`[ERR_INVALID_CALLBACK]: Callback must be a function
[MJSONWP]     at makeStatsCallback (fs.js:178:11)
[MJSONWP]     at fs.stat (fs.js:914:14)
[MJSONWP]     at Object.fs.stat (ELECTRON_ASAR.js:306:16)
[MJSONWP]     at Object.stat (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/release/util.js:16:23)
[MJSONWP]     at Object.ret [as stat] (eval at makeNodePromisifiedEval (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/promisify.js:184:12), :15:23)
[MJSONWP]     at _bluebird.default.map (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/util.js:260:72)
[MJSONWP]     at tryCatcher (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/release/util.js:16:23)
[MJSONWP]     at MappingPromiseArray._promiseFulfilled (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/release/map.js:68:38)
[MJSONWP]     at MappingPromiseArray.PromiseArray._iterate (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/release/promise_array.js:115:31)
[MJSONWP]     at MappingPromiseArray.init (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/release/promise_array.js:79:10)
[MJSONWP]     at MappingPromiseArray._asyncInit (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/release/map.js:37:10)
[MJSONWP]     at _drainQueueStep (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/release/async.js:97:12)
[MJSONWP]     at _drainQueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/release/async.js:86:9)
[MJSONWP]     at Async._drainQueues (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/release/async.js:102:5)
[MJSONWP]     at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/bluebird/js/release/async.js:15:14)
[MJSONWP]     at runCallback (timers.js:696:18)
[MJSONWP]     at tryOnImmediate (timers.js:667:5)
[MJSONWP]     at processImmediate (timers.js:649:5)
[HTTP] <-- POST /wd/hub/session 500 1562 ms - 164
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 1 ms - 57
[HTTP] `

**Comment by igor-dmck** [comment]
After updating Appium from version 1.15.1 to 1.16.0 I've the same issue as for @KseniaBudlianska

**Comment by galaninaa** [comment]
> After updating Appium from version 1.15.1 to 1.16.0 I've the same issue as for @KseniaBudlianska

The same error for 1.16.0. Any resolve?

**Comment by KazuCocoa** [comment]
Around `(/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/util.js:260:72) [MJSONWP] at tryCatcher` is probably https://github.com/appium/appium-support/blob/master/lib/util.js#L264-L271 , but I have no idea except for NodeJS version for now...

Did the error also happen against Appium CLI directly?
(I mean sending a session create request to an appium cli via non appium desktop client.)

**Comment by navdiana** [comment]
Also having same problem.

**Comment by Jonathan0137** [comment]
I used to have the same problem. But it worked for me when I downgrade from 1.16.0 to 1.15.1.

**Comment by KazuCocoa** [comment]
Could @KseniaBudlianska or someone share the Appium CLI's full log as [GIST](https://gist.github.com/) to track the entire behaviour? (Running  outside Appium Desktop.)
I mean:

```bash
$ npm install -g appium # expected 1.16.0
$ appium # start appium server
```

and send a create session request to the server.
Then, please ensure your installing NodeJS version is 10+.

**Comment by lgh06** [comment]
same here, 1.16.0 appium desktop, for iOS testing, on my mac.  
1.16.0 appium from npm works fine.

**Comment by galaninaa** [comment]
Fixed for me using appium@beta from npm.

**Comment by KazuCocoa** [comment]
Definitely it happened on Appium 1.16.0 while 1.15.1 worked.
Perhaps npm build was broken in 1.16.0, but still not sure this issue's original error on 1.15.1.

**Comment by KazuCocoa** [comment]
It seems appium 1.16.0 packaged as AD is not good.
AD 1.16.0 + appium 1.16.0 (CLI) local host connection worked.

**Comment by ganjarpanji** [comment]
so the solution is downgrade to 1.15.1?

**Comment by KazuCocoa** [comment]
Yes

**Comment by sebaranguiz** [comment]
Hi, I got rid off this bug using the following versions:

`$ appium -v`
1.16.0
`$ node -v`
v12.16.1
`$ npm -v`
6.13.7
